name: ${project.artifactId}
main: me.tWizT3d_dreaMr.ShopAddon.main
version: ${project.version}
authors: [tWizT3d_dreaMr, TonyJamesStark]
depend: [Shop]
softdepend: [Essentials]
commands:
   # the following functionality is now supported by the native Shop plugin
   # sa:
   #    description: checks shop signs log
   #    usage: sa check <page>
   # SASQLConversion:
   #    description: Converts my logging to official logging
   #    usage: SASQLConversion
   ShopNotifications:
      description: Changes your shop notification settings
      usage: ShopNotifications
   SearchShops:
      description: Search Shops
      usage: SearchShops <Item> or SearchShops player <playername/nickname> or SearchShops loredName <CustomItemName>
api: ${apiVersion}
api-version: ${apiVersion}